/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_flexcan.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitUART functional group */
/* Definition of peripheral ID */
#define BOARD_LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define BOARD_LPUART1_CLOCK_SOURCE 80000000UL

/* Definitions for BOARD_InitCAN2 functional group */
/* Definition of peripheral ID */
#define BOARD_CAN2_PERIPHERAL CAN2
/* Definition of the clock source frequency */
#define BOARD_CAN2_CLOCK_SOURCE 40000000UL
/* CAN2 interrupt vector ID (number). */
#define BOARD_CAN2_FLEXCAN_IRQN CAN2_IRQn
/* CAN2 interrupt handler identifier. */
#define BOARD_CAN2_FLEXCAN_IRQHANDLER CAN2_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpuart_config_t BOARD_LPUART1_config;
extern const flexcan_config_t BOARD_CAN2_config;
/* Message buffer 1 configuration structure */
extern const flexcan_rx_mb_config_t BOARD_CAN2_rx_mb_config_1;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitUART(void);

void BOARD_InitCAN2(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
